version: 0.0
os: linux
files:
  - source: index.html  # Remove the leading slash
    destination: /var/www/html/
  - source: scripts/  # Ensure the scripts folder is copied
    destination: /home/ubuntu/scripts/

hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/install_dependencies  # Use absolute path after deployment
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ubuntu/scripts/start_httpd  # Same here
      timeout: 300
      runas: root
