version: 0.2
phases:
  install:
    commands:
      - echo Installing HTTPD
      - sudo apt -y update
      - sudo apt install httpd -y
  build:
    commands:
      - echo build started on 'date'
      - cp /index.html /var/www/html/
  post_build:
    commands:
      - echo configuring HTTPD
artifacts:
  files:
    - /var/www/html/index.html
