version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update -y
      - sudo apt-get install -y apache2
  build:
    commands:
      - echo "Build started on $(date)"
  post_build:
    commands:
      - echo "Configuration completed."
artifacts:
  files:
    - '**/*'
